### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by markusgft** [ipab-slmc/pinocchio_catkin#1]
Dear @wxmerkt 
First of all, I really like the idea of having a catkin-wrapper around pinocchio, thanks for the great contribution!
Could you please clarify what the license of this release is, and add a respective license statement somewhere to the repo?
Best and thanks!

**Comment by wxmerkt** [comment]
Hi Markus,
Since this is just a wrapper around Pinocchio-v2, I think it should have the same license as Pinocchio itself (BSD-2).
We've released pinocchio via this repository to the ROS buildfarm and it's available on kinetic and melodic (`sudo apt install ros-[distro]-pinocchio`, albeit it may only be after the next sync). 

As of now, we haven't compiled it with the hpp-fcl bindings - but these will likely come with the next release. Happy to also see contributions and further feedback :)

Best,
Wolfgang

**Comment by markusgft** [comment]
Dear @wxmerkt, 
I'd like to briefly follow up on this thread, although it's been a while. How often does the pinocchio version on the ROS buildfarm get updated or forwarded to the latest developments on the master branch of the main repo? Is there a regular schedule?
Thanks a lot in advance!
...

Edit: I care mostly about the *-melodic-* release.

**Comment by wxmerkt** [comment]
Dear @markusgft,
I am just about to update it today: There have been major changes in the way we package. We also had to wait for upstream to fix the version configuration and Python install paths. This may break people's current usage. 

We are now moving from a `catkin` wrapper to a third-party build as per [ROS REP-136](https://www.ros.org/reps/rep-0136.html). This means that instead of using

```cmake
find_package(catkin REQUIRED COMPONENTS pinocchio)
```

the usage for Pinocchio is (until CMake targets are exported)

```cmake
find_package(PkgConfig)
pkg_check_modules(pinocchio REQUIRED pinocchio)
```

An example for how to adapt it is here: https://github.com/ipab-slmc/exotica/pull/675/files

I will release version `2.2.0` today along with EigenPy version `1.6.8`. From this point on, we deprecate this `pinocchio_catkin` catkin wrapper. EigenPy and Pinocchio can now be built directly in a catkin workspace from the upstream repositories. This makes it effortless to have code compatible between the ROS buildfarm, robotpkg, and source and allows us to iterate and release quicker

I hope this helps - very happy to hear your feedback and thoughts.

Best wishes,
Wolfgang

**Comment by markusgft** [comment]
Thanks @wxmerkt , we'll be waiting for the release and make our changes as you suggested.
